version: '3.5'
services:
  hive-base-js:
    build:
      context: ../../../../containers/hive-base-js
      # dockerfile: Dockerfile.full
      # dockerfile: Dockerfile.slim
      target: development
    image: hive-base-js:development
    container_name: hive-base-js
    environment:
      ACTOR: ContentActor
      ACTOR_LIB: hive-io-rest-example
      ACTOR_URLS: "/contents,/contents/:id"
      CLUSTER_SIZE: 1
      SECURE: "true"
      SSL_CERT: "/opt/app/cert/ssl-cert.pem"
      SSL_KEY: "/opt/app/cert/ssl-key.pem"
      TELEMETRY: "true"
      TELEMETRY_PLUGINS: '{"mongodb":{"enabled":true,"path":"@opentelemetry/plugin-mongodb"},"mongoose":{"enabled":true,"path":"@wdalmut/opentelemetry-plugin-mongoose"}}'
      TELEMETRY_URL_METRICS: "http://collector:55681/v1/metrics"
      TELEMETRY_URL_TRACES: "http://collector:55681/v1/trace"
      MONGO_URL: "mongodb://mongo:27017/contents"
    depends_on:
      - collector
      - mongo
    command: npm run dev
    ports:
      - 443:3000
    volumes:
      - ../../../../containers/hive-base-js:/opt/app:rw
      - /opt/app/node_modules
      - /opt/app/cert
      # NOTE: the following shared volumes are only necessary for framework development
      - ../../../../packages/hive-js-rest-example:/opt/app/node_modules/hive-io-rest-example:rw
      - ../../../../packages/hive-js:/opt/app/node_modules/hive-io:rw
      - ../../../../packages/hive-js-rest-example/node_modules/@opentelemetry/plugin-mongodb:/opt/app/node_modules/@opentelemetry/plugin-mongodb:rw
      - ../../../../packages/hive-js-rest-example/node_modules/@wdalmut/opentelemetry-plugin-mongoose:/opt/app/node_modules/@wdalmut/opentelemetry-plugin-mongoose:rw
      - ../../../../packages/hive-js-rest-example/node_modules/shimmer:/opt/app/node_modules/shimmer:rw
      - ../../../../packages/hive-js-rest-example/node_modules/mongodb:/opt/app/node_modules/mongodb:rw
      - ../../../../packages/hive-js-rest-example/node_modules/bl:/opt/app/node_modules/bl:rw
      - ../../../../packages/hive-js-rest-example/node_modules/bson:/opt/app/node_modules/bson:rw
      - ../../../../packages/hive-js-rest-example/node_modules/denque:/opt/app/node_modules/denque:rw
      - ../../../../packages/hive-js-rest-example/node_modules/require_optional:/opt/app/node_modules/require_optional:rw
    networks:
      - hive-io
  mongo:
    image: mongo:4.4.3
    container_name: mongo
    networks:
      - hive-io
    restart: on-failure

  # telelemtry
  collector:
    image: otel/opentelemetry-collector:0.17.0
    container_name: collector
    command: ["--config=/conf/collector-config.yml", "--log-level=WARN"]
    depends_on:
      - zipkin
    volumes:
      - ../../../collector/collector-config.yml:/conf/collector-config.yml
    networks:
      - hive-io
    restart: on-failure
  zipkin:
    image: openzipkin/zipkin:2.23.2
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - hive-io
    restart: on-failure

# networking
networks:
  hive-io:
    driver: bridge
