version: '3.5'
services:
  hive-base-js:
    build: .
    image: hive-base-js:production
    container_name: hive-base-js
    environment:
      ACTOR: PostActor
      ACTOR_LIB: hive-io-rest-example
      ACTOR_URLS: "/posts,/posts/:postId"
      CLUSTER_SIZE: 1
      SECURE: "true"
      MONGO_URL: "mongodb://mongo:27017/post"
      FLUENTD_HOST: fluentd
      FLUENTD_PORT: 24224
      FLUENTD_TIMEOUT: 3.0
      FLUENTD_RECONNECT: 600000
    depends_on:
      - fluentd
      - mongo
    ports:
      - 443:3000
    networks:
      - hive-io
  fluentd:
    image: fluent/fluentd:v1.11.4-2.0
    container_name: fluentd
    networks:
      - hive-io
    restart: on-failure
  mongo:
    image: mongo:4.4.1
    container_name: mongo
    networks:
      - hive-io
    restart: on-failure

# networking specifics
networks:
  hive-io:
    driver: bridge
