version: '3.5'
services:
  hive-base-js:
    build: .
    image: hive-base-js:production
    environment:
      ACTOR: PostActor
      ACTOR_LIB: hive-io-rest-example
      CLUSTER_SIZE: 1
      SECURE: "true"
      MONGO_URL: "mongodb://mongo:27017/post"
      FLUENTD_HOST: fluentd
      FLUENTD_PORT: 24224
      FLUENTD_TIMEOUT: 3.0
      FLUENTD_RECONNECT: 600000
    depends_on:
      - mongo
      - fluentd
    ports:
      - 443:3000
    networks:
      - hive-io
  fluentd:
    image: fluent/fluentd:v1.9.2-1.0
    networks:
      - hive-io
    restart: on-failure
  mongo:
    image: mongo:4.2.3
    networks:
      - hive-io
    restart: on-failure

# networking specifics
networks:
  hive-io:
    driver: bridge
